### ISSUE TITLE
Import Keys

### ISSUE THREAD

**Issue by ajay340** [henryboldi/felony#54] opened 2016-07-08 15:38 UTC
How do I import my private key in felony? I am on the fixed version of 0.10.3 on debian. When I click open on the file tab or Ctr + O nothing happens.

**Comment by tobycyanide-pwr** [comment] 2016-07-08 15:56
Duplicate of #34

**Comment by selfagency** [comment] 2016-07-08 16:10
+1 on OS X. I would also like to be able to import my existing private and public keys.

**Comment by greg-js** [comment] 2016-07-09 15:44
You can already import public keys. As for importing private keys, you can just paste it into `~/felony.json`. Also, I made a straightforward edit to the UI to allow pasting in an existing key in the UI [here](https://github.com/greg-js/felony/tree/importkey) ([linux & OSX releases here](https://github.com/greg-js/felony/releases)) (remember to delete/move your existing `~/.felony.json` first or it will just pick up on what you already have there).

Not sure if my approach fits in well with the existing style but if there's some positive feedback I'll make it look a bit better and submit a PR on Monday.

**Comment by jarrydfillmore** [comment] 2016-07-11 20:10
Nice!

**Comment by TechyPeople** [comment] 2016-08-04 22:44
Duplicate of #7 and #34.  Closing this down, we're working on adding a simpler version of the version from @greg-js and we'll post updates on #7.

**Closed by TechyPeople** 2016-08-04 22:44 UTC
Labels: duplicate, enhancement
