### ISSUE TITLE
Windows Installer does not work

### ISSUE THREAD

**Issue by Marc66** [henryboldi/felony#79] opened 2016-08-16 06:18 UTC
#### What's this issue about?
When I try to install on Windows 7 64 bits, I get an error message and nothing gets installed. Why not make this application portable (no installer)?

#### Expected behavior
I expect the installer to install the application

#### Actual behavior
The installer stops with an error. When I close the error message, it pops up again. I end up with multiple Felony.exe processes. Attached is the error message and Process list:

![error_message](https://cloud.githubusercontent.com/assets/11850067/17689695/a798702a-6389-11e6-924c-6dbc41ef5c65.jpg)

![windows_task_manager](https://cloud.githubusercontent.com/assets/11850067/17689705/b85d77a2-6389-11e6-9bd3-acae46b06643.jpg)

#### Steps to reproduce
Run the installer, wait, see

#### Environment
Windows 7 Enterprise SP1 64 bits
8 GB RAM
Enough disk space
Local Admin on machine

**Comment by gliwka** [comment] 2016-08-16 14:31
Duplicate of #14

**Closed** 2016-09-21 08:28 UTC
Labels: duplicate
