### ISSUE TITLE
Suggestion: Change app name

### ISSUE THREAD

**Issue by CameronBanga** [henryboldi/felony#39] opened 2016-07-05 14:45 UTC
Would love to use this with my privacy conscious friends, but no way I would consider it with he current name. People are already a bit spooked by privacy, given the current political climate. So the last thing I would want to do is be like "Hey friends, check out this great privacy service. It's called Felony. No don't worry, it's not a crime or anything. Sure it sounds weird, but trust me."

**Comment by octalmage** [comment] 2016-07-05 17:44
There's some discussion around the name going on in #35.

**Comment by todb-r7** [comment] 2016-07-06 14:25
Certainly a dupe of #35. @henryboldi should close this issue.

**Closed** 2016-07-07 17:39 UTC
