### ISSUE TITLE
Blank application window on startup 

### ISSUE THREAD

**Issue by danwxyz** [henryboldi/felony#70] opened 2016-07-30 17:56 UTC
On Ubuntu 16.04.1 x86_64, Felony starts up with a blank application window:

![felony](https://cloud.githubusercontent.com/assets/7411154/17272162/634492c0-565d-11e6-8961-d7fadf962143.png)

This is the binary from Felony-linux-0.10.3-x64.zip

**Comment by frankcash** [comment] 2016-08-04 10:24
Can you open the developer consoles and post your logs

**Comment by danwxyz** [comment] 2016-08-04 12:52
There is no developer console that I can find in the GUI.

**Comment by daveloyall** [comment] 2016-08-04 15:07
I have a similar problem.  Except, I get what appears to be an empty Electron demo application.  See screen shot.

![image](https://cloud.githubusercontent.com/assets/1524866/17406992/46a7a2e8-5a2b-11e6-8a4d-984db844ed0e.png)

**Comment by daveloyall** [comment] 2016-08-04 16:59
OK, this issue is a duplicate of #20 and #36 and #33.

@brbsix found a solution shown here: https://github.com/brbsix/felony/commit/a880bf61de2c2b5517410fa46f45d324f6848eb0

The latest release here on @henryboldi's repo is 21 commits behind master.  One of those commits would appear to fix this problem: https://github.com/henryboldi/felony/commit/95e3596efa1bfbd57186c8bdc134719f796484e7

So, perhaps @henryboldi can just make another release from the current master (assuming that other issues don't prevent that).

Or, @brbsix, consider merging some of the other commits from @henryboldi to your own repo...

**Comment by frankcash** [comment] 2016-08-04 17:18
Yes, the title bar update is the solution.

**Comment by frankcash** [comment] 2016-08-04 18:29
Please let me know if this issue still persists.

**Closed** 2016-08-04 18:31 UTC
Labels: bug, duplicate

**Comment by SkyzohKey** [comment] 2016-08-16 14:43
The issue still happens with version 0.10.3 (I'm on fedora 23, running budgie-desktop).

**Comment by frankcash** [comment] 2016-08-16 14:47
@SkyzohKey Hmm I see, I'll try and get new releases up this weekend .  Sorry for the delay.

**Comment by SkyzohKey** [comment] 2016-08-16 14:48
Don't apologize for that, I know those situations where you think an issue has been fixed in the latest release but users still get it x)

Anyway, I'd suggest an hotkey to enable the Inspector, would be better for us to debug ;)
